// <auto-generated />
namespace YMovies.MovieDbService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdateRelationshipBetweenMovieSeriesAndStatistic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateRelationshipBetweenMovieSeriesAndStatistic));
        
        string IMigrationMetadata.Id
        {
            get { return "202112240659221_UpdateRelationshipBetweenMovieSeriesAndStatistic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
